eureka:
  instance:
    prefere-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    servie-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http:localhost:8761/eureka}
